#!/usr/bin/env bash
set -e

help() {
  cat <<EOF
Manage GitHub Projects(beta) seamlessly from the command line.

USAGE
  gh project-manager <command> <subcommands> [flags]

COMMANDS
  add:              Add issues to project
  init:             Initialize a new project
  view:             View project specific properties and children

FLAGS
  --help, -h        Show help for command

EXAMPLES
  $ gh project-manager init
  $ gh project-manager view issues user 4 --legacy > issues.json
  $ gh project-manager add issues --project-type org --project-num 1 --path issues.json

LEARN MORE
  Use 'gh project-manager <command> --help' for more information about a command.
  Read the documentation at https://github.com/jnmiller-va/gh-project-manager
EOF
}

BASEDIR=$(dirname "$0")

if [ "$1" == init ] || [ "$1" == view ] || [ "$1" == add ]; then
  command=$1
  shift
  exec "$BASEDIR"/command/"$command".sh "$@"
fi

while [ $# -gt 0 ]; do
  case "$1" in
  -h|--help)
    help
    exit 0
    ;;
  *)
    help >&2
    exit 1
    ;;
  esac
  shift
done
